# Generated by Django 4.0.2 on 2022-02-28 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testRoot', '0040_saveplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDetailTokyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testRoot.tokyocity')),
            ],
        ),
    ]
